USE superstore_db;

/*
SUPERSTORE SALES ANALYSIS PROJECT

Concepts Used:
1. Subqueries
2. CTEs
3. Window Functions
4. Joins
5. Business Analysis Queries
*/

-- View raw imported data

SELECT * 
FROM superstore_raw
LIMIT 10;

-- Total records

SELECT COUNT(*) AS Total_Records
FROM superstore_raw;


/*
CREATE TABLES
*/

-- Customer Master Table

CREATE TABLE customers AS
SELECT DISTINCT
    Customer_ID,
    Customer_Name,
    Segment,
    Country,
    City,
    State,
    Region
FROM superstore_raw;


-- Product Master Table

CREATE TABLE products AS
SELECT DISTINCT
    Product_ID,
    Product_Name,
    Category,
    Sub_Category
FROM superstore_raw;


-- Orders Table

CREATE TABLE orders AS
SELECT
    Order_ID,
    Order_Date,
    Ship_Date,
    Ship_Mode,
    Customer_ID,
    Product_ID,
    Sales,
    Quantity,
    Discount,
    Profit
FROM superstore_raw;


/*
VERIFY TABLE CREATION
*/

-- View customer table

SELECT *
FROM customers
LIMIT 5;

-- View product table

SELECT *
FROM products
LIMIT 5;

-- View orders table

SELECT *
FROM orders
LIMIT 5;


/*
BASIC DATA EXPLORATION
*/

-- Total customers

SELECT COUNT(*) AS Total_Customers
FROM customers;


-- Total products

SELECT COUNT(*) AS Total_Products
FROM products;


-- Total orders

SELECT COUNT(*) AS Total_Orders
FROM orders;


-- Distinct categories

SELECT DISTINCT Category
FROM products;


-- Distinct regions

SELECT DISTINCT Region
FROM customers;


/*
SUBQUERY 1

Orders with sales greater than average sales
*/

SELECT *
FROM orders
WHERE Sales >
(
    SELECT AVG(Sales)
    FROM orders
);

-- Insight:
-- These orders have sales higher than the overall average sales value.


/*
SUBQUERY 2

Highest sales order for each customer
*/

SELECT *
FROM orders o
WHERE Sales =
(
    SELECT MAX(Sales)
    FROM orders
    WHERE Customer_ID = o.Customer_ID
);

-- Insight:
-- Finds the highest value order placed by each customer.


/*
CTE 1

Total sales generated by each customer
*/

WITH customer_sales AS
(
    SELECT
        Customer_ID,
        SUM(Sales) AS Total_Sales
    FROM orders
    GROUP BY Customer_ID
)

SELECT *
FROM customer_sales
ORDER BY Total_Sales DESC;

-- Insight:
-- Helps identify customers contributing the most revenue.


/*
CTE 2

Total profit generated by each customer
*/

WITH customer_profit AS
(
    SELECT
        Customer_ID,
        SUM(Profit) AS Total_Profit
    FROM orders
    GROUP BY Customer_ID
)

SELECT *
FROM customer_profit
ORDER BY Total_Profit DESC;

-- Insight:
-- Shows which customers are the most profitable.


/*
WINDOW FUNCTION

ROW_NUMBER
*/

SELECT
    Customer_ID,
    Sales,

    ROW_NUMBER() OVER
    (
        PARTITION BY Customer_ID
        ORDER BY Sales DESC
    ) AS Order_Number

FROM orders;

-- Insight:
-- Assigns a unique sequence number to each order per customer.


/*
WINDOW FUNCTION

RANK
*/

SELECT
    Customer_ID,
    SUM(Sales) AS Total_Sales,

    RANK() OVER
    (
        ORDER BY SUM(Sales) DESC
    ) AS Customer_Rank

FROM orders
GROUP BY Customer_ID;

-- Insight:
-- Ranks customers based on their total sales.


/*
WINDOW FUNCTION

DENSE_RANK
*/

SELECT
    Customer_ID,
    SUM(Sales) AS Total_Sales,

    DENSE_RANK() OVER
    (
        ORDER BY SUM(Sales) DESC
    ) AS Dense_Rank_Value

FROM orders
GROUP BY Customer_ID;

-- Insight:
-- Similar to rank but without skipping rank numbers.


/*
FINAL TASK

JOIN + CTE + WINDOW FUNCTION
*/

WITH customer_sales AS
(
    SELECT
        Customer_ID,
        SUM(Sales) AS Total_Sales
    FROM orders
    GROUP BY Customer_ID
)

SELECT
    c.`Customer ID`,
    c.`Customer Name`,
    cs.Total_Sales,

    RANK() OVER
    (
        ORDER BY cs.Total_Sales DESC
    ) AS Sales_Rank

FROM customers c
JOIN customer_sales cs
ON c.`Customer ID` = cs.Customer_ID

ORDER BY Sales_Rank;

-- Insight:
-- Combines joins, CTEs and window functions to rank customers by sales.


-- Extra business-oriented SQL queries created independently for additional analysis and practice.


/*
TOP 10 CUSTOMERS BY SALES
*/

WITH customer_sales AS
(
    SELECT
        Customer_ID,
        SUM(Sales) AS Total_Sales
    FROM orders
    GROUP BY Customer_ID
)

SELECT *
FROM customer_sales
ORDER BY Total_Sales DESC
LIMIT 10;

-- Insight:
-- Identifies the most valuable customers.


/*
BOTTOM 10 CUSTOMERS BY SALES
*/

WITH customer_sales AS
(
    SELECT
        Customer_ID,
        SUM(Sales) AS Total_Sales
    FROM orders
    GROUP BY Customer_ID
)

SELECT *
FROM customer_sales
ORDER BY Total_Sales ASC
LIMIT 10;

-- Insight:
-- Highlights customers with the lowest contribution to sales.


/*
CUSTOMERS HAVING ONLY ONE ORDER
*/

SELECT
    Customer_ID,
    COUNT(Order_ID) AS Total_Orders
FROM orders
GROUP BY Customer_ID
HAVING COUNT(Order_ID) = 1;

-- Insight:
-- These customers may require retention strategies.


/*
CUSTOMERS ABOVE AVERAGE TOTAL SALES
*/

WITH customer_sales AS
(
    SELECT
        Customer_ID,
        SUM(Sales) AS Total_Sales
    FROM orders
    GROUP BY Customer_ID
)

SELECT *
FROM customer_sales
WHERE Total_Sales >
(
    SELECT AVG(Total_Sales)
    FROM customer_sales
);

-- Insight:
-- Shows customers performing above average.


/*
TOP 5 PROFITABLE CUSTOMERS
*/

SELECT
    Customer_ID,
    SUM(Profit) AS Total_Profit
FROM orders
GROUP BY Customer_ID
ORDER BY Total_Profit DESC
LIMIT 5;

-- Insight:
-- Identifies customers generating maximum profit.


/*
MOST PROFITABLE CATEGORY
*/

SELECT
    p.Category,
    SUM(o.Profit) AS Total_Profit
FROM orders o
JOIN products p
ON o.Product_ID = p.Product_ID
GROUP BY p.Category
ORDER BY Total_Profit DESC;

-- Insight:
-- Helps identify the category contributing the highest profit.


/*
REGION WISE SALES ANALYSIS
*/

SELECT
    c.Region,
    SUM(o.Sales) AS Region_Sales
FROM orders o
JOIN customers c
ON o.Customer_ID = c.Customer_ID
GROUP BY c.Region
ORDER BY Region_Sales DESC;

-- Insight:
-- Compares sales performance across regions.


/*
AVERAGE DISCOUNT BY CATEGORY
*/

SELECT
    p.Category,
    ROUND(AVG(o.Discount),2) AS Avg_Discount
FROM orders o
JOIN products p
ON o.Product_ID = p.Product_ID
GROUP BY p.Category;

-- Insight:
-- Shows which categories receive higher discounts.


/*
TOP SELLING PRODUCTS
*/

SELECT
    p.Product_Name,
    SUM(o.Quantity) AS Total_Quantity_Sold
FROM orders o
JOIN products p
ON o.Product_ID = p.Product_ID
GROUP BY p.Product_Name
ORDER BY Total_Quantity_Sold DESC
LIMIT 10;

-- Insight:
-- Identifies the most demanded products.


/*
CUSTOMERS GENERATING PROFIT WITH ABOVE AVERAGE DISCOUNT
*/

SELECT
    Customer_ID,
    SUM(Profit) AS Total_Profit,
    AVG(Discount) AS Avg_Discount
FROM orders
GROUP BY Customer_ID
HAVING AVG(Discount) >
(
    SELECT AVG(Discount)
    FROM orders
)
AND SUM(Profit) > 0;

-- Insight:
-- Finds customers who remain profitable despite receiving higher discounts.


/*
RANK PRODUCTS WITHIN EACH CATEGORY
*/

SELECT
    p.Category,
    p.Product_Name,
    SUM(o.Sales) AS Product_Sales,

    RANK() OVER
    (
        PARTITION BY p.Category
        ORDER BY SUM(o.Sales) DESC
    ) AS Category_Rank

FROM orders o
JOIN products p
ON o.Product_ID = p.Product_ID

GROUP BY
    p.Category,
    p.Product_Name;

-- Insight:
-- Ranks products against competitors within the same category.


